/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c			                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: aklimchu <aklimchu@student.hive.fi>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/05/21 14:51:07 by aklimchu          #+#    #+#             */
/*   Updated: 2024/05/22 14:26:31 by aklimchu         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include <limits.h>
#include "ft_printf.h"

// The function for testing ft_printf project.
int	main()
{
	char	*ptr = "MOI";
	int		i, j;

	printf("The first result is generated by original printf, the second result by my program. Then the difference in the return of 2 programs is calculated Then the difference in the return of 2 programs is calculated.\n\n");

	i = printf("%p %p\n", NULL, NULL);
	j = ft_printf("%p %p\n", NULL, NULL);
	printf("%d\n\n", i  - j);

	printf("%d\n\n", i  - j);
	i = printf("MAKE YOUR DAY\n");
	j = ft_printf("MAKE YOUR DAY\n");

	printf("%d\n\n", i  - j);
	i = printf("x - %x\n", -12345);
	j = ft_printf("x - %x\n", -12345);

	printf("%d\n\n", i  - j);
	i = printf("X - %X\n", 123345);
	j = ft_printf("X - %X\n", 123345);

	printf("%d\n\n", i  - j);
	i = printf("x - %x\n", 0);
	j = ft_printf("x - %x\n", 0);

	printf("%d\n\n", i  - j);
	i = printf("c - %c\n", 'a');
	j = ft_printf("c - %c\n", 'a');

	printf("%d\n\n", i  - j);
	i = printf("s - %s\n", "MY NAME IS");
	j = ft_printf("s - %s\n", "MY NAME IS");

	printf("%d\n\n", i  - j);
	i = printf("p - %p\n", ptr);
	j = ft_printf("p - %p\n", ptr);

	printf("%d\n\n", i  - j);
	i = printf("d - %d\n", -155);
	j = ft_printf("d - %d\n", -155);

	printf("%d\n\n", i  - j);
	i = printf("%d mix of d and u %u\n", -5, 10000);
	j = ft_printf("%d mix of d and u %u\n", -5, 10000);

	printf("%d\n\n", i  - j);
	i = printf("percentage sign - %%\n");
	j = ft_printf("percentage sign - %%\n");
}
